language: go
sudo: false
go:
  - "1.12"
  - "1.13"
  - stable

install:
  # install golangci-lint to ./bin
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.31.0

script:
  - ./bin/golangci-lint run ./...
  - go test ./...